name: Deploy to Server

on:
  push:
    branches:
      - main # Деплой запускается при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}          # IP-адрес сервера
        username: ${{ secrets.DEPLOY_USER }}      # Пользователь на сервере
        key: ${{ secrets.DEPLOY_SSH_KEY }}        # Приватный ключ SSH (в GitHub Secrets)
        port: 22                                  # Порт SSH
        script: |
          echo "Deploying project to server"

          # Создаем папку для проекта (если её нет)
          mkdir -p /var/www/yandex

          # Копируем файлы проекта на сервер
          rsync -avz --delete -e "ssh -p 22" ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/yandex/

          # Перезапускаем Nginx (если используется)
          sudo systemctl reload nginx
