name: Deploy to Server

on:
  push:
    branches:
      - main # Деплой запускается при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }} # IP-адрес сервера
        username: ${{ secrets.DEPLOY_USER }} # Имя пользователя на сервере
        key: ${{ secrets.DEPLOY_SSH_KEY }} # SSH-ключ
        port: 22
        script: |
          echo "Deploying project to server"

          # Удаляем старые файлы
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "rm -rf /var/www/yandex/*"

          # Копируем файлы с помощью rsync
          rsync -avz --delete -e "ssh -p 22" ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/yandex

          # Перезапускаем Nginx
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "sudo systemctl reload nginx"
